version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    hostname: app
    image: test_app
    depends_on:
      - test_db
  test_db:
    image: postgres
    container_name: test_db
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    container_name: nginx
    expose:
      - 8080
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:8080"
    depends_on:
      - app
volumes:
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dbdata