openapi: 3.0.3
info:
  title: Library Project API
  version: 1.0.0
  description: Library Project API
paths:
  /api/v1/book_copies/:
    get:
      operationId: book_copies_list
      tags:
      - book_copies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookCopy'
          description: ''
    post:
      operationId: book_copies_create
      tags:
      - book_copies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCopy'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BookCopy'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BookCopy'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
          description: ''
  /api/v1/book_copies/{id}/:
    get:
      operationId: book_copies_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Экземпляр книги.
        required: true
      tags:
      - book_copies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
          description: ''
    put:
      operationId: book_copies_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Экземпляр книги.
        required: true
      tags:
      - book_copies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCopy'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BookCopy'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BookCopy'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
          description: ''
    patch:
      operationId: book_copies_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Экземпляр книги.
        required: true
      tags:
      - book_copies
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBookCopy'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBookCopy'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBookCopy'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
          description: ''
    delete:
      operationId: book_copies_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Экземпляр книги.
        required: true
      tags:
      - book_copies
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/books/:
    get:
      operationId: books_list
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      parameters:
        - name: author
          in: query
          description: Book's author id filtering.
          required: false
          schema:
            type: integer
        - name: publishing_year
          in: query
          description: Book's publishing year filtering.
          required: false
          schema:
            type: integer
        - name: department
          in: query
          description: Book's department id filtering.
          required: false
          schema:
            type: integer
        - name: is_book_available
          in: query
          description: Book's availability filtering.
          required: false
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
          description: ''
    post:
      operationId: books_create
      tags:
      - books
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Book'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
  /api/v1/books/{id}/:
    get:
      operationId: books_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Книга.
        required: true
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    put:
      operationId: books_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Книга.
        required: true
      tags:
      - books
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Book'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    patch:
      operationId: books_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Книга.
        required: true
      tags:
      - books
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBook'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBook'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: ''
    delete:
      operationId: books_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Книга.
        required: true
      tags:
      - books
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/customers/:
    get:
      operationId: customers_list
      tags:
      - customers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerList'
          description: ''
    post:
      operationId: customers_create
      tags:
      - customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetail'
          description: ''
  /api/v1/customers/{id}/:
    get:
      operationId: customers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Посетитель.
        required: true
      tags:
      - customers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetail'
          description: ''
    put:
      operationId: customers_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Посетитель.
        required: true
      tags:
      - customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomerDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetail'
          description: ''
    patch:
      operationId: customers_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Посетитель.
        required: true
      tags:
      - customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCustomerDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCustomerDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCustomerDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetail'
          description: ''
    delete:
      operationId: customers_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Посетитель.
        required: true
      tags:
      - customers
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/departments/:
    get:
      operationId: departments_list
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
          description: ''
    post:
      operationId: departments_create
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Department'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Department'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Department'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: ''
  /api/v1/departments/{id}/:
    get:
      operationId: departments_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Отдел.
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: ''
    put:
      operationId: departments_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Отдел.
        required: true
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Department'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Department'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Department'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: ''
    patch:
      operationId: departments_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Отдел.
        required: true
      tags:
      - departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDepartment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDepartment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDepartment'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: ''
    delete:
      operationId: departments_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Отдел.
        required: true
      tags:
      - departments
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название книги
          maxLength: 255
        authors:
          type: array
          items:
            type: string
        publishing_year:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Год издания
        department:
          type: string
        is_book_available:
          type: boolean
          readOnly: true
      required:
      - authors
      - department
      - id
      - is_book_available
      - name
      - publishing_year
    BookCopy:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        book:
          type: integer
          title: Книга
        taken_by:
          type: string
      required:
      - book
      - id
    CustomerDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Имя посетителя
          maxLength: 255
        taken_books:
          type: array
          items:
            type: string
      required:
      - id
      - name
    CustomerList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Имя посетителя
          maxLength: 255
        taken_book_count:
          type: integer
          readOnly: true
      required:
      - id
      - name
      - taken_book_count
    Department:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название отдела
          maxLength: 255
      required:
      - id
      - name
    PatchedBook:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название книги
          maxLength: 255
        authors:
          type: array
          items:
            type: string
        publishing_year:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Год издания
        department:
          type: string
        is_book_available:
          type: boolean
          readOnly: true
    PatchedBookCopy:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        book:
          type: integer
          title: Книга
        taken_by:
          type: string
    PatchedCustomerDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Имя посетителя
          maxLength: 255
        taken_books:
          type: array
          items:
            type: string
    PatchedDepartment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название отдела
          maxLength: 255
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
